# Generated by Django 5.0.7 on 2024-07-23 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='parkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.IntegerField()),
                ('TWA', models.IntegerField()),
                ('FWA', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='parkhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('TWA', 'TWA'), ('FWA', 'FWA')], default='FWA', max_length=5)),
                ('VehicleNumber', models.CharField(max_length=10)),
                ('Lot', models.IntegerField()),
                ('In', models.TimeField()),
                ('Out', models.TimeField()),
                ('Fee', models.IntegerField()),
                ('Level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_management.parkspace')),
            ],
        ),
    ]
