# Generated by Django 5.0.7 on 2024-07-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_management', '0002_parkspace_parkhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkhistory',
            name='Level',
            field=models.IntegerField(),
        ),
    ]
