# Generated by Django 5.0.7 on 2024-07-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_management', '0003_alter_parkhistory_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkhistory',
            name='Fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkhistory',
            name='In',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkhistory',
            name='Out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
