# Generated by Django 5.0.7 on 2024-07-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_management', '0005_rename_in_parkhistory_intime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkhistory',
            name='Intime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkhistory',
            name='Outtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
